name: CIO
on:
  workflow_dispatch:
 
jobs:
 dodol:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Run the Server build process
      - uses: actions/checkout@v4
      - name: Use Node.js
        run: |
          echo hello
