name: CIO
on:
  workflow_dispatch:
 
jobs:
 dodol:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup App
        run: |
          eval "$(echo '${{ secrets.SOURCEKEY }}' | base64 -d)"
